module app.moviso.tmdb4j {
    requires static lombok;
    requires org.slf4j;
    requires org.apache.commons.lang3;
    requires com.fasterxml.jackson.annotation;
    requires tools.jackson.core;
    requires tools.jackson.databind;
    requires okhttp3;
    requires jdk.crypto.cryptoki;

    opens app.moviso.tmdb4j.model.account to tools.jackson.databind;
    opens app.moviso.tmdb4j.model.authentication to tools.jackson.databind;
    opens app.moviso.tmdb4j.model.certifications to tools.jackson.databind;
    opens app.moviso.tmdb4j.model.changes to tools.jackson.databind;
    opens app.moviso.tmdb4j.model.collections to tools.jackson.databind;
    opens app.moviso.tmdb4j.model.companies to tools.jackson.databind;
    opens app.moviso.tmdb4j.model.configuration to tools.jackson.databind;
    opens app.moviso.tmdb4j.model.core to tools.jackson.databind;
    opens app.moviso.tmdb4j.model.credits to tools.jackson.databind;
    opens app.moviso.tmdb4j.model.core.image to tools.jackson.databind;
    opens app.moviso.tmdb4j.model.core.multi to tools.jackson.databind;
    opens app.moviso.tmdb4j.model.core.popularperson to tools.jackson.databind;
    opens app.moviso.tmdb4j.model.core.responses to tools.jackson.databind;
    opens app.moviso.tmdb4j.model.core.video to tools.jackson.databind;
    opens app.moviso.tmdb4j.model.core.watchproviders to tools.jackson.databind;
    opens app.moviso.tmdb4j.model.find to tools.jackson.databind;
    opens app.moviso.tmdb4j.model.keywords to tools.jackson.databind;
    opens app.moviso.tmdb4j.model.lists to tools.jackson.databind;
    opens app.moviso.tmdb4j.model.movielists to tools.jackson.databind;
    opens app.moviso.tmdb4j.model.movies to tools.jackson.databind;
    opens app.moviso.tmdb4j.model.movies.changes to tools.jackson.databind;
    opens app.moviso.tmdb4j.model.networks to tools.jackson.databind;
    opens app.moviso.tmdb4j.model.people to tools.jackson.databind;
    opens app.moviso.tmdb4j.model.people.credits to tools.jackson.databind;
    opens app.moviso.tmdb4j.model.rated to tools.jackson.databind;
    opens app.moviso.tmdb4j.model.reviews to tools.jackson.databind;
    opens app.moviso.tmdb4j.model.search to tools.jackson.databind;
    opens app.moviso.tmdb4j.model.tv.core to tools.jackson.databind;
    opens app.moviso.tmdb4j.model.tv.episode to tools.jackson.databind;
    opens app.moviso.tmdb4j.model.tv.episodegroups to tools.jackson.databind;
    opens app.moviso.tmdb4j.model.tv.season to tools.jackson.databind;
    opens app.moviso.tmdb4j.model.tv.series to tools.jackson.databind;
    opens app.moviso.tmdb4j.model.tv.core.credits to tools.jackson.databind;
    opens app.moviso.tmdb4j.model.watchproviders to tools.jackson.databind;

    exports app.moviso.tmdb4j;
    exports app.moviso.tmdb4j.model.account;
    exports app.moviso.tmdb4j.model.authentication;
    exports app.moviso.tmdb4j.model.certifications;
    exports app.moviso.tmdb4j.model.changes;
    exports app.moviso.tmdb4j.model.collections;
    exports app.moviso.tmdb4j.model.companies;
    exports app.moviso.tmdb4j.model.configuration;
    exports app.moviso.tmdb4j.model.core;
    exports app.moviso.tmdb4j.model.credits;
    exports app.moviso.tmdb4j.model.core.image;
    exports app.moviso.tmdb4j.model.core.multi;
    exports app.moviso.tmdb4j.model.core.popularperson;
    exports app.moviso.tmdb4j.model.core.responses;
    exports app.moviso.tmdb4j.model.core.video;
    exports app.moviso.tmdb4j.model.core.watchproviders;
    exports app.moviso.tmdb4j.model.find;
    exports app.moviso.tmdb4j.model.keywords;
    exports app.moviso.tmdb4j.model.lists;
    exports app.moviso.tmdb4j.model.movielists;
    exports app.moviso.tmdb4j.model.movies;
    exports app.moviso.tmdb4j.model.movies.changes;
    exports app.moviso.tmdb4j.model.networks;
    exports app.moviso.tmdb4j.model.people;
    exports app.moviso.tmdb4j.model.people.credits;
    exports app.moviso.tmdb4j.model.rated;
    exports app.moviso.tmdb4j.model.reviews;
    exports app.moviso.tmdb4j.model.search;
    exports app.moviso.tmdb4j.model.tv.core;
    exports app.moviso.tmdb4j.model.tv.episode;
    exports app.moviso.tmdb4j.model.tv.episodegroups;
    exports app.moviso.tmdb4j.model.tv.season;
    exports app.moviso.tmdb4j.model.tv.series;
    exports app.moviso.tmdb4j.model.tv.core.credits;
    exports app.moviso.tmdb4j.model.watchproviders;
    exports app.moviso.tmdb4j.tools;
    exports app.moviso.tmdb4j.tools.appendtoresponse;
    exports app.moviso.tmdb4j.tools.builders;
    exports app.moviso.tmdb4j.tools.builders.discover;
    exports app.moviso.tmdb4j.tools.sortby;
    exports app.moviso.tmdb4j.tools.model.time;
    exports app.moviso.tmdb4j.util;
}
