module app.moviso.tmdb4j {
    requires static lombok;
    requires org.slf4j;
    requires org.apache.commons.lang3;
    requires com.fasterxml.jackson.annotation;
    requires com.fasterxml.jackson.core;
    requires com.fasterxml.jackson.databind;
    requires java.net.http;
    requires jdk.crypto.cryptoki;

    opens app.moviso.tmdb4j.model.account to com.fasterxml.jackson.databind;
    opens app.moviso.tmdb4j.model.authentication to com.fasterxml.jackson.databind;
    opens app.moviso.tmdb4j.model.certifications to com.fasterxml.jackson.databind;
    opens app.moviso.tmdb4j.model.changes to com.fasterxml.jackson.databind;
    opens app.moviso.tmdb4j.model.collections to com.fasterxml.jackson.databind;
    opens app.moviso.tmdb4j.model.companies to com.fasterxml.jackson.databind;
    opens app.moviso.tmdb4j.model.configuration to com.fasterxml.jackson.databind;
    opens app.moviso.tmdb4j.model.core to com.fasterxml.jackson.databind;
    opens app.moviso.tmdb4j.model.core.image to com.fasterxml.jackson.databind;
    opens app.moviso.tmdb4j.model.core.multi to com.fasterxml.jackson.databind;
    opens app.moviso.tmdb4j.model.core.popularperson to com.fasterxml.jackson.databind;
    opens app.moviso.tmdb4j.model.core.responses to com.fasterxml.jackson.databind;
    opens app.moviso.tmdb4j.model.core.video to com.fasterxml.jackson.databind;
    opens app.moviso.tmdb4j.model.core.watchproviders to com.fasterxml.jackson.databind;
    opens app.moviso.tmdb4j.model.find to com.fasterxml.jackson.databind;
    opens app.moviso.tmdb4j.model.keywords to com.fasterxml.jackson.databind;
    opens app.moviso.tmdb4j.model.lists to com.fasterxml.jackson.databind;
    opens app.moviso.tmdb4j.model.movielists to com.fasterxml.jackson.databind;
    opens app.moviso.tmdb4j.model.movies to com.fasterxml.jackson.databind;
    opens app.moviso.tmdb4j.model.movies.changes to com.fasterxml.jackson.databind;
    opens app.moviso.tmdb4j.model.networks to com.fasterxml.jackson.databind;
    opens app.moviso.tmdb4j.model.people to com.fasterxml.jackson.databind;
    opens app.moviso.tmdb4j.model.people.credits to com.fasterxml.jackson.databind;
    opens app.moviso.tmdb4j.model.rated to com.fasterxml.jackson.databind;
    opens app.moviso.tmdb4j.model.reviews to com.fasterxml.jackson.databind;
    opens app.moviso.tmdb4j.model.search to com.fasterxml.jackson.databind;
    opens app.moviso.tmdb4j.model.tv.core to com.fasterxml.jackson.databind;
    opens app.moviso.tmdb4j.model.tv.episode to com.fasterxml.jackson.databind;
    opens app.moviso.tmdb4j.model.tv.episodegroups to com.fasterxml.jackson.databind;
    opens app.moviso.tmdb4j.model.tv.season to com.fasterxml.jackson.databind;
    opens app.moviso.tmdb4j.model.tv.series to com.fasterxml.jackson.databind;
    opens app.moviso.tmdb4j.model.tv.core.credits to com.fasterxml.jackson.databind;
    opens app.moviso.tmdb4j.model.watchproviders to com.fasterxml.jackson.databind;

    exports app.moviso.tmdb4j;
    exports app.moviso.tmdb4j.model.account;
    exports app.moviso.tmdb4j.model.authentication;
    exports app.moviso.tmdb4j.model.certifications;
    exports app.moviso.tmdb4j.model.changes;
    exports app.moviso.tmdb4j.model.collections;
    exports app.moviso.tmdb4j.model.companies;
    exports app.moviso.tmdb4j.model.configuration;
    exports app.moviso.tmdb4j.model.core;
    exports app.moviso.tmdb4j.model.core.image;
    exports app.moviso.tmdb4j.model.core.multi;
    exports app.moviso.tmdb4j.model.core.popularperson;
    exports app.moviso.tmdb4j.model.core.responses;
    exports app.moviso.tmdb4j.model.core.video;
    exports app.moviso.tmdb4j.model.core.watchproviders;
    exports app.moviso.tmdb4j.model.find;
    exports app.moviso.tmdb4j.model.keywords;
    exports app.moviso.tmdb4j.model.lists;
    exports app.moviso.tmdb4j.model.movielists;
    exports app.moviso.tmdb4j.model.movies;
    exports app.moviso.tmdb4j.model.movies.changes;
    exports app.moviso.tmdb4j.model.networks;
    exports app.moviso.tmdb4j.model.people;
    exports app.moviso.tmdb4j.model.people.credits;
    exports app.moviso.tmdb4j.model.rated;
    exports app.moviso.tmdb4j.model.reviews;
    exports app.moviso.tmdb4j.model.search;
    exports app.moviso.tmdb4j.model.tv.core;
    exports app.moviso.tmdb4j.model.tv.episode;
    exports app.moviso.tmdb4j.model.tv.episodegroups;
    exports app.moviso.tmdb4j.model.tv.season;
    exports app.moviso.tmdb4j.model.tv.series;
    exports app.moviso.tmdb4j.model.tv.core.credits;
    exports app.moviso.tmdb4j.model.watchproviders;
    exports app.moviso.tmdb4j.tools;
    exports app.moviso.tmdb4j.tools.appendtoresponse;
    exports app.moviso.tmdb4j.tools.builders;
    exports app.moviso.tmdb4j.tools.builders.discover;
    exports app.moviso.tmdb4j.tools.sortby;
    exports app.moviso.tmdb4j.tools.model.time;
    exports app.moviso.tmdb4j.util;
}
